import{a as u,S as P,i as d}from"./assets/vendor-527658dd.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function c(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=c(t);fetch(t.href,o)}})();const v=document.querySelector(".form-search"),l=document.querySelector(".btn-more"),p=document.querySelector(".gallery-list"),f=document.querySelector(".loader-wrapper"),L="42027651-7bedd500762feb24dffc0a2de";u.defaults.baseURL="https://pixabay.com/api/";const s={key:L,q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:1};let r=0;const O={captionsData:"alt",captionPosition:"bottom",captionDelay:250},q={theme:"dark",class:"izi-toast-error-style",title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",iconUrl:"./img/octagon.svg",position:"topRight",maxWidth:"25%"},S={position:"topRight",message:"We're sorry, there are no more posts to load"},w=new P(".gallery-list a",O);v.addEventListener("submit",M);l.addEventListener("click",x);function x(){g("flex"),h(),y(),m(f.getBoundingClientRect().height)}function M(e){e.preventDefault(),$(),g("flex"),p.innerHTML="",s.q=e.target.elements.search.value,e.target.elements.perPage.value!==""?s.per_page=e.target.elements.perPage.value:s.per_page=40,y(),this.reset()}function m(e){scrollBy({top:e,behavior:"smooth"})}function $(){r=0,s.page=1}function D(e){r=Math.ceil(e.totalHits/s.per_page)}function h(){if(r>1?l.style.display="block":l.style.display="none",s.page>=r&&r!==0)return l.style.display="none",d.error(S)}function g(e){f.style.display=e}async function y(){try{const e=await E();r===0?D(e):console.log("getTotalPages not run"),h(),e.totalHits>0?T(e):d.error(q),g("none"),s.page++}catch(e){console.log(e)}}async function E(){return(await u.get("",{params:s})).data}const R=e=>e.map(({largeImageURL:a,webformatURL:c,tags:i,likes:t,views:o,comments:n,downloads:b})=>`<li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${c}" alt="${i}" width="360" height="200" loading="lazy"/>
        </a>
        <div class="item-info">
        <p class="item-info-p">Likes <span>${t}</span></p>
        <p class="item-info-p">Views <span>${o}</span></p>
        <p class="item-info-p">Comments <span>${n}</span></p>
        <p class="item-info-p">Downloads <span>${b}</span></p>
        </div>
        </li>`).join("");function T(e){p.insertAdjacentHTML("beforeend",R(e.hits)),w.refresh(),m(p.childNodes[0].getBoundingClientRect().height*2)}
//# sourceMappingURL=commonHelpers.js.map
